#David(?)  httpS?
#nota1: este request me fallaba sin http://...

#que archivo deberia contener estos settings?
#nota2: se murio la compu dende me habias 
#apoyado con fractal (perdi la referencia) :(
@host=  http://localhost:3000
@email=javierzavalaponce@gmail.com
@password=123456


### Sign Up
POST {{host}}/users/sign-up
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "age": 17
}

### Sign In
# @name signIn
POST {{host}}/users/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Get Profile
#GET {{host}}/users/profile
#Content-Type: application/json
#Authorization: Bearer {{signIn.response.body.token_jwt}}

### Get Tasks
GET {{host}}/tasks/

### Get Task by ID
GET {{host}}/tasks/1